version: '3.9'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - .env
    networks:
      - nestnet

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: RessourcesRelationnelles
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - nestnet

volumes:
  mysql-data:

networks:
  nestnet:
